### ISSUE TITLE
Criar classe Sound

### ISSUE THREAD

**Issue by rodrigocam** [Desenho2018-1/simian#2]
Criar uma classe que será a representação de um som nos jogos. Para a implementação aconselha-se se basear nas fontes:

- [Sound fgaTatics](https://github.com/fgaTactics/tecprog2017.1/blob/devel/gameEngine/GameSounds.py)
- [pygame mixer](https://www.pygame.org/docs/ref/mixer.html)

**Comment by Joranhezon** [comment]
Fechada [neste](https://github.com/Desenho2018-1/simian/pull/17) pull request
