### ISSUE TITLE
Corrigir Paths da aplicação

### ISSUE THREAD

**Issue by pablodiegoss** [Desenho2018-1/simian#27]
## Bug

Alguns caminhos da aplicação são absolutos, outros relativos. Em alguns métodos você indica o caminho do arquivo, em outros um objeto. 

## Checklist

- [X] A issue possui label
- [ ] A issue possui print de tela se necessário
- [X] A issue possui nome significativo

**Comment by alaxalves** [comment]
Provavelmente é isso que ta causando esse erro no travis:
![image](https://user-images.githubusercontent.com/19597045/41162903-9f653388-6b0d-11e8-83b4-ccee351c020c.png)

**Comment by Rdlenke** [comment]
O bug persiste.
